using Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace Demo.Data.ModelsConfiguration
{
    class DepartmentConfiguration : IEntityTypeConfiguration<Department>
    {
        public void Configure(EntityTypeBuilder<Department> department)
        {
           
                department.ToTable("Departments", "Sales");//To make table for this entity in specific schema
                                                        //this is if you not add new property in the "DbContext" class to map Department class as table Departments in DB
                                                        //DbSet<Department> Departments {get;set;}
                                                        //or use this overload if you need to put the table in specific schema - if the schema not existed in DB, it will created.

            department.HasKey(D => D.DeptId);
            department.Property(D => D.DeptId)
                 .UseIdentityColumn(10, 10);//To Change The Default of Identity(Seed,Increment) from (1,1) to (10,10)

            //department.Property(D => D.DeptId)
            // .ValueGeneratedNever();//To Stop/Disable The Identity Constraint and add values to this column as you need.

            //department.Property(D => D.DeptId)
            // .HasDefaultValueSql("NEWID()");//When Add new Row in the column "DeptId" and don't specify the value for "DeptId"
            //                                  //the value will set as default by calling the Sql Method "Guid()" to generate Random & Unique Id - Generated By Sql in every time i will add row in column DeptId
            //                                  //HasDefaultValue("Eslam") => if you use this overload the default value for column "DeptId" if you not enter "Id" when add new row will be "Eslam" - Generated By App not Sql.

            department.Property(D => D.DeptName)
                 .HasColumnName("DepartmentName")
                 .HasColumnType("varchar")//Change the default/convention dataType from nVarchar(max) to varchar
                 .HasMaxLength(20)
                 .IsRequired(false)
                 .HasDefaultValue("HR");

            department.Property(D => D.DateOfCreation)//The Default Type when mapping is "Date" as sql type
                                                 //.IsRequired(false)//Will throw exception when try to add migration because the type of this property is DateTime and the datetime Type not accept null in C#.
                 .HasAnnotation("DataType", "Date")//To make annotation "DataType" on this column to be "Date" when displaying it's values in ASP.NET Core App.
                                                   //.HasDefaultValue(DateTime.Now);//The Default Value will be assigned as the DateTime when make/Add the migration 
                                                   //                               // so if migration made in defaultValue: new DateTime(2025, 3, 1, 16, 21, 31, 642, DateTimeKind.Local)
                                                   //                               //This will be the dateTime value for any department row will added to Department table
                                                   //                               //For any object/row added to the DB the DateOfCreation of it will be same as the date of migration done in APP new DateTime(2025, 3, 1, 16, 21, 31, 642, DateTimeKind.Local)


                .HasDefaultValueSql("GetDate()");//This Method "GetDate()" Executed in DB when Add new Department object/Row
                                                 //To add the result of it in the column DateOfCreation.
                                                 //After insert new Department object/row in the DB - This Function "GetDate()" will executed
                                                 //And the value will putted in the column "DateOfCreation"
                                                 //And After this if you try to update any column value of this object/row
                                                 //The value of the column "DateOfCreation" Which is the result of Execute "GetDate()" will still the same [Not Affected when Modify the Department Row/Object] 
                                                 //So this mean the function "GetDate()" when use "HasDefaultValueSql("GetDate())"
                                                 //Will executed once when add new Department row/object and assign it's value to column "DateOfCreation".
                                                 //And The Value Can Be Manually Set.

            //.HasComputedColumnSql("GetDate()");//Will Executed Every time i make Change/Modify on this department Object/Row.
            //                                   //Automatically The value of column "DateOfCreation" will Recalculated every time you try to change value of any column of the inserted department row/object
            //                                   //I use it if i have column like "LastUpdate" that track the DateTime of last update on the inserted department Row/Object.   
            //                                   //And The Value Can't Be Manually Set.


            department.Ignore(D => D.Serial);//To Say That this property will not mapped as column in DB.



        }
    }
}
