using Demo.Data.Models;
using Microsoft.EntityFrameworkCore;

namespace Demo
{
    internal class Program
    {
        static void Main(string[] args)
        {
            #region Part 01 Mapping Ways  - 2. Data Annotations

            ///There Are 4 Ways That EF core Support For Mapping Classes [DbContext - Domain Models] To [Tables - Views] in DB
            /// 1- By Convention
            /// 2- Data Annotations [Set Of Attributes[Classes]]
            /// 3- Fluent API
            ///
            ///We Will Discuss The Data Annotations [Set of Attributes] Way in This Context => 
            /// - Attributes use the decorator design pattern As behavior Not Implementation [Attributes Classes Internally not using Decorator Design Pattern]
            ///    Mean That I have Property not has specific behavior and i need this property to use this behavior
            ///    So I Make Attribute on it [Add to it specific behavior].
            ///    Make Decoration to it.
            ///    So Attributes are set of Behaviors.
            /// -With other meaning => I have property in class Employee Called "Code" And I need it to mapped as PK Column in DB
            ///   But With Convention Way This not will be mapped as PK
            ///   Because In Convention Way The PK column Must be named "Id" or "ModelName+Id".
            ///   So We let this Property "Code" to have new behavior to be "PK" by Make Attribute [KeyAttribute] on it [Use Data Annotation Way] to be mapped as PK Column.
            ///
            ///I don't work using specific Way => I understand the Convention Way Will
            ///And then if i need the mapping of this convention way => Ok use it.
            ///If You need to add extra or change the default behavior => use another way to meet your needs.
            ///
            ///When We will Work On ASP.NET Core Web Application
            /// -Every Class Model Will Be has View[HTML Page] Specific for this class
            /// -Throw This page the user can create new instance from the class and
            /// -And inside this page there is HTML Input for each and every property to let user enter values to those properties
            /// -So if i need to make validations on this input values - I make Validation Data Annotations [Properties] on top of the property in the class model.
            ///
            ///If there is property in Domain Model Class use the identity(1,1)
            ///And you need to add data in Database 
            ///And make object from class like Employee
            ///You can't set this property with value because it is auto generated by sql server service.
            ///
            ///Any Data Annotation that used as validation has default error Message - but you can override this default error message.

            #endregion

            #region Part 02 Mapping Ways (Fluent APIs)

            ///It's Mapping Way used to configure entity Properties/Columns ,Relationships.
            ///it gives you more control over the database schema and relationships compared to Data Annotations.
            ///There are some configuration on entity properties that i can't configure it using Convention or Data Annotations Way
            ///So I use Fluent APIs to make this Configuration.
            ///
            ///We Work By Fluent APIs by 2 ways:
            ///1- Define The Fluent APIs Configuration inside the "OnModelCreating" in Your "DbContext" class that inherit it from the base "DbContext" Class
            ///2- Through Separate Configuration Classes using the IEntityTypeConfiguration<T> interface.
            ///   [Make Class That configure each model in Application].
            ///
            ///
            ///Now => We will use the first Way of Configuring => Define the Configuration Inside "OnModelCreating" Method.
            ///This Method "OnModelCreating" will Called When Add Migration.
            ///This method inherited from the base class "DbContext", but the body of it inside the "DbContext" class is empty
            ///So i remove it and make my own configuration.
            ///This Method Take parameter of type ModelBuilder : "ModelBuilder modelBuilder"
            ///modelBuilder.Entity<Employee>() -> To Hold The Entity/Table Employee And Make Configuration On It.
            ///modelBuilder.Entity<Employee>().HasKey(E => E.Code) -> To Say that the Code Column/Property will be the PK. 
            ///modelBuilder.Entity<Employee>().Property(E => E.Name) => To Hold Specific Property and make configuration it.
            ///
            ///Most of Fluent APIs are represented inside DB.
            ///If you need to make validations and view errors -> use Data Annotations.
            ///
            ///If the return type is "EntityTypeBuilder" -> You Make Configuration on The Entity/Table
            ///If the return type is "PropertyTypeBuilder" -> You Make Configuration on The Property/Column
            ///
            ///We use The Fluent APIs way always in 2 cases:
            ///1- If we need to make property/Column in database that not be in the class model in application.
            ///modelBuilder.Entity<Employee>()
            ///            .Property<string>("EmpName");//If Found property in class "Employee" of type string and called "EmpName" will use it
            ///                                         //if not it will define "EmpName" as Shadow Property => Mean That this "EmpName" will be column in DB but it not represented as property in the model "Employee"
            ///   
            ///2- If we work on Type Class/Model That not in the current project
            ///    I only have the IL code of this class - Not have the source Code of it.
            ///    I need to configure Class to map it to table but i don't have the source code
            ///    So I can't use the Data Annotations Way because i can't access the file of class
            ///    And the Configuration of convention way not like what i need, so i use Fluent APIs way. 
            /// -So I Add Reference from this project that contain this class in my project
            /// -But this project not in same Solution, if it in the same solution, i can access it and edit the source code.
            /// -After Add reference it will be in Dependencies/Assemblies/ProjectName.dll
            ///-Assemblies => Projects that my project depend on it but it not in the same solution and i have IL code of it only not the source code so i can't edit on it.
            ///
            ///After Make this => I add new property in the "DbContext" Class of type "DbSet<Department> Departments"
            ///To map this class that came from the Remote/External project inside the DB.

            #endregion
        }
    }
}
