using Common;
using Demo.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;

namespace Demo
{
    internal class Program
    {
        static void Main(string[] args)
        {
            #region Part 01 Mapping Ways  - 2. Data Annotations

            ///There Are 4 Ways That EF core Support For Mapping Classes [DbContext - Domain Models] To [Tables - Views] in DB
            /// 1- By Convention
            /// 2- Data Annotations [Set Of Attributes[Classes]]
            /// 3- Fluent API
            ///
            ///We Will Discuss The Data Annotations [Set of Attributes] Way in This Context => 
            /// - Attributes use the decorator design pattern As behavior Not Implementation [Attributes Classes Internally not using Decorator Design Pattern]
            ///    Mean That I have Property not has specific behavior and i need this property to use this behavior
            ///    So I Make Attribute on it [Add to it specific behavior].
            ///    Make Decoration to it.
            ///    So Attributes are set of Behaviors.
            /// -With other meaning => I have property in class Employee Called "Code" And I need it to mapped as PK Column in DB
            ///   But With Convention Way This not will be mapped as PK
            ///   Because In Convention Way The PK column Must be named "Id" or "ModelName+Id".
            ///   So We let this Property "Code" to have new behavior to be "PK" by Make Attribute [KeyAttribute] on it [Use Data Annotation Way] to be mapped as PK Column.
            ///
            ///I don't work using specific Way => I understand the Convention Way Will
            ///And then if i need the mapping of this convention way => Ok use it.
            ///If You need to add extra or change the default behavior => use another way to meet your needs.
            ///
            ///When We will Work On ASP.NET Core Web Application
            /// -Every Class Model Will Be has View[HTML Page] Specific for this class
            /// -Throw This page the user can create new instance from the class and
            /// -And inside this page there is HTML Input for each and every property to let user enter values to those properties
            /// -So if i need to make validations on this input values - I make Validation Data Annotations [Properties] on top of the property in the class model.
            ///
            ///If there is property in Domain Model Class use the identity(1,1)
            ///And you need to add data in Database 
            ///And make object from class like Employee
            ///You can't set this property with value because it is auto generated by sql server service.
            ///
            ///Any Data Annotation that used as validation has default error Message - but you can override this default error message.

            #endregion

            #region Part 02 Mapping Ways -> 3.1- (Fluent APIs) by override the function "OnModelCreating()" in the "DbContext" Class and configure classes inside it.

            /// - Use Fluent APIs Way by override the function "OnModelCreating()" in the "DbContext" Class and configure classes inside it.
            ///It's Mapping Way used to configure entity Properties/Columns ,Relationships.
            ///it gives you more control over the database schema and relationships compared to Data Annotations.
            ///There are some configuration on entity properties that i can't configure it using Convention or Data Annotations Way
            ///So I use Fluent APIs to make this Configuration.
            ///
            ///We Work By Fluent APIs by 2 ways:
            ///1- Define The Fluent APIs Configuration inside the "OnModelCreating" in Your "DbContext" class that inherit it from the base "DbContext" Class
            ///2- Through Separate Configuration Classes using the IEntityTypeConfiguration<T> interface.
            ///   [Make Class That configure each model in Application].
            ///
            ///
            ///Now => We will use the first Way of Configuring => Define the Configuration Inside "OnModelCreating" Method.
            ///This Method "OnModelCreating" will Called When Add Migration.
            ///This method inherited from the base class "DbContext", but the body of it inside the "DbContext" class is empty
            ///So i remove it and make my own configuration.
            ///This Method Take parameter of type ModelBuilder : "ModelBuilder modelBuilder"
            ///modelBuilder.Entity<Employee>() -> To Hold The Entity/Table Employee And Make Configuration On It.
            ///modelBuilder.Entity<Employee>().HasKey(E => E.Code) -> To Say that the Code Column/Property will be the PK. 
            ///modelBuilder.Entity<Employee>().Property(E => E.Name) => To Hold Specific Property and make configuration it.
            ///
            ///Most of Fluent APIs are represented inside DB.
            ///If you need to make validations and view errors -> use Data Annotations.
            ///
            ///If the return type is "EntityTypeBuilder" -> You Make Configuration on The Entity/Table
            ///If the return type is "PropertyTypeBuilder" -> You Make Configuration on The Property/Column
            ///
            ///We use The Fluent APIs way always in 2 cases:
            ///1- If we need to make property/Column in database that not be in the class model in application.
            ///modelBuilder.Entity<Employee>()
            ///            .Property<string>("EmpName");//If Found property in class "Employee" of type string and called "EmpName" will use it
            ///                                         //if not it will define "EmpName" as Shadow Property => Mean That this "EmpName" will be column in DB but it not represented as property in the model "Employee"
            ///   
            ///2- If we work on Type Class/Model That not in the current project
            ///    I only have the IL code of this class - Not have the source Code of it.
            ///    I need to configure Class to map it to table but i don't have the source code
            ///    So I can't use the Data Annotations Way because i can't access the file of class
            ///    And the Configuration of convention way not like what i need, so i use Fluent APIs way. 
            /// -So I Add Reference from this project that contain this class in my project
            /// -But this project not in same Solution, if it in the same solution, i can access it and edit the source code.
            /// -After Add reference it will be in Dependencies/Assemblies/ProjectName.dll
            ///-Assemblies => Projects that my project depend on it but it not in the same solution and i have IL code of it only not the source code so i can't edit on it.
            ///
            ///After Make this => I add new property in the "DbContext" Class of type "DbSet<Department> Departments"
            ///To map this class that came from the Remote/External project inside the DB.

            #endregion

            #region Part 03 Mapping Ways -> 3.2- (Fluent APIs- Configuration classes)

            ///Mapping Fluent API Configuration Through Separate Configuration Classes.
            ///Using The IEntityTypeConfiguration<T> interface.
            ///This Improve Code Organization And Maintainability.
            ///
            ///In this Way, Instead of make configuration for All Models/Tables inside one function "OnModelCreating()" that called when "Add-Migration" to apply configurations inside it
            ///We make Configuration Class For Each Entity/Model/Table and make this class implement the interface IEntityTypeConfiguration<T>
            ///T -> Represent the Type/Class/Table 
            ///And When Implement this interface, it has method "Configure(EntityTypeBuilder<T> builder)"
            ///That i need to provide implementation for it - Make configuration of class/Table inside it.
            ///
            ///And Then To Apply This Configuration on the class/Table that you make
            ///Go To The Class "DbContext" And inside the "OnModelCreating()"
            ///Add this Line -> modelBuilder.ApplyConfiguration<Employee>(new EmployeeConfiguration());
            ///This method<T> is generic,T represent the type/Model/Class/Table and take object from any class implement the generic interface "IEntityTypeConfiguration<T>"
            ///
            ///So for each configuration class -> you must add this line of applying configuration inside the "OnModelCreating()" method inside "DbContext" class.
            ///
            ///You Can Automatically Let when Add new Configuration Class and make configuration in it by using the "Reflection" in C#.
            ///Let EF Automatically Apply this Configuration made in the current executing Assembly
            ///By add this line in the method OnModelCreating() ->  modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly())
            ///In Run Time EF Core Will Apply Configuration For All Classes that implement the interface IEntityTypeConfiguration<T> in the current executing Assembly.
            ///But use this only when you have large scale project that in it many configuration Classes.
            ///If there are like 2 or 3 configuration class -> add line of apply[Make object from the config class] Configuration for each config class inside the method "OnModelCreating()"
            ///
            ///We always use the last way of mapping => FluentAPIs With Configuration Classes because it is organized
            ///DataAnnotations is readable but it make the model class file Crowded [زحمه]

            #endregion

            #region Part 04 Query Object Model - CRUD Operations

            ///When We Work On Data Using EFCore
            ///We Will Work By LinQ Against EFCore [LinQ To EFCore]
            ///To Query Object Model
            ///Mean Query Row/object Of the Class/Table [CRUD Operations On the data].
            ///
            ///To Query object model
            ///We need first to open connection between Application And Database.
            ///To Make Crud Operations on data in DB throw the APP.
            ///
            ///Required [As Keyword] => Ensure that the property must assigned with value in compilation Time when make object from the class, you must assign this property using constructor or object initializer [Required Key word Not-Mapped in DB]
            /// -Like in the property "PhoneNumber" inside the Employee Class -> public required string PhoneNumber { get; set; }
            ///You can say the property is required and also of nullable Type like this -> public required string? PhoneNumber { get; set; }
            ///in this case "Required" is just validation for APP and not mapped in DB, but string? will mapped in DB as column of type nvarchar(max) that accept null. 
            ///
            ///Required [As DataAnnotation (Attribute)] => Validate that you set value to this property that you put "Required" attribute but in Run Time
            ///If you not set value to it -> throw exception.
            /// [Required]
            /// public string Email { get; set; }
            ///Required Attribute Mapped in DB.
            ///
            ///If you have property/column that you put identity constraint on it and mapped it to DB
            ///You can't set value to this property when make object from class
            ///Because it is readonly and auto generated by SQl.
            ///
            ///Note -> 
            ///You make object from "CompanyDbContext" which inherit from "DbContext" that has property called "ChangeTracker"
            ///Which mean that you have change tracker for every object you make
            ///And every object you make has state
            ///And state of it changed based on it's relation with Database.
            ///So if you need to know state of any object based on relation with DB
            ///call method Entry<T>(T entity) that take the object that you need to view state of it with DB and return type "EntityEntry" and then call the state property that is inside class "EntityEntry".
            ///Which of type Enum "EntityState" that can hold 4 state Labels of objects that change tracker track them -> 
            /// 1-Detached (0) -> mean that the object not related to DB - not founded as row/field in DB.
            /// 2-Unchanged (1) -> The object is in DB but not changed -The state of it in "APP" like state of it in "DB" - محصلش عليه أي تغيير
            /// 3-Deleted (2) -> The object is in DB but Removed from APP 
            /// 4-Modified (3) -> The object is in DB but State of it in APP not like State of it in DB - حصل على الاوبجت تغيير في الكود. 
            /// 5-Added (4) -> The object is not in DB but you Add it in APP throw method but not make saveChanges().
            ///
            ///You can disable change Tracker property on all objects using this line/command
            /// context.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;

            //using CompanyDbContext context = new CompanyDbContext();

            //Employee emp01 = new Employee()
            //{
            //    PhoneNumber = "01022010887",
            //    Age = 30,
            //    Email = "eslam.saadany22@gmail.com",
            //    password = "P@ssw0rd",
            //    Salary = 40000,
            //    Name = "Eslam Ashraf"
            //};

            ////context.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.TrackAll;//Default
            //
            //Console.WriteLine(context.Entry<Employee>(emp01).State);//Detached[Default]
            //emp01.Age = 50;//Modify
            //Console.WriteLine(context.Entry<Employee>(emp01).State);//still Detached because you Change tracker only track objects that returned from LinQ query.
            //So we need to add it inside Database.

            #region 01 - Insert/Add New Record/object of type Employee in table Employees in Database.

            //Console.WriteLine(context.Entry<Employee>(emp01).State);//Detached

            //context.Employees.Add(emp01);//Approach01 - Not really add the object in DB - it just convert the change tracker state of object from Detached to Added.
            //context.Set<Employee>().Add(emp01);//Approach02 - if you don't have the table as "DbSet" in the "DbContextClass"- Not really add the object in DB - it just convert the change tracker state of object from Detached to Added.
            //context.Add<Employee>(emp01);//Approach03 - Not really add the object in DB - it just convert the change tracker state of object from Detached to Added.
            //context.Entry<Employee>(emp01).State = EntityState.Added;//Approach04 - Not really add the object in DB - it just convert the change tracker state of object from Detached to Added.

            //Console.WriteLine("==After Adding To DbSet==");

            //Console.WriteLine(context.Entry<Employee>(emp01).State);//Added [Added Locally in App not in DB].
            //Console.WriteLine($"emp01.Code: {emp01.Code}");//0 [Default value of type "int"] - Because this property not initialized in object initializer when make the object
            //                                               //because this property/column has identity constraint and also this object still not in DB so it's code not set with value by SQL.

            //context.SaveChanges();//Saves all changes made in this context to DB
            ////This method will automatically call method "ChangeTracker.DetectChanges()"
            ////to discover any changes to entity instances before saving to the underlying database
            ////and convert this code to SQL Commands and execute it [Every program run will executed this method].

            //Console.WriteLine("==After SaveChanges()==");

            //Console.WriteLine(context.Entry<Employee>(emp01).State);//UnChanged - object in DB like this object in APP.
            //Console.WriteLine($"emp01.Code: {emp01.Code}");//1 - because this object added to db as the first object/row with identity start from 1 and increment by 1.                                                         //because this property/column has identity constraint and also this object still not in DB so it's code not set with value by SQL.

            #endregion

            #region 02 - Select/Retrieve Data From Table In Database - Not need to Apply change tracker on this returned object because i need only display it not make modify on it.
            ////Not need to Apply change tracker on this returned object
            ////because i need only display it not make modify on it.

            //var employee01 = context.Employees.AsNoTracking().FirstOrDefault(e => e.Salary == 40000);//Translated As Top(1) in SQL
            ////var employee01 = context.Employees.SingleOrDefault(e => e.Salary == 40000);//Translated As Top(2) in SQL - because if there are more than one match the condition will throw exception

            //if (employee01 is not null)
            //{
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//Detached
            //    Console.WriteLine($"[Code: {employee01.Code}] - [Name: {employee01.Name}] - [Salary: {employee01.Salary}] - [NetSalary: {employee01.NetSalary}] - [Email: {employee01.Email}] - [password: {employee01.password}]");
            //}

            #endregion

            #region 03 - Modify/Update on retrieving data from table in DB.

            #region 03.1 - If Change Tracking on object is Activated

            //var employee01 = context.Employees.FirstOrDefault(e => e.Salary == 40000);//Translated As Top(1) in SQL

            //if (employee01 is not null)
            //{
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//UnChanged
            //    Console.WriteLine($"[Code: {employee01.Code}] - [Name: {employee01.Name}] - [Salary: {employee01.Salary}] - [NetSalary: {employee01.NetSalary}] - [Email: {employee01.Email}] - [password: {employee01.password}]");

            //    employee01.Name = "Amr";//Change

            //    Console.WriteLine("==After Change==");
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//Modified
            //    Console.WriteLine($"Name After Change => {employee01.Name}");//"Amr" - But still not affected the DB - Still "Eslam Ashraf" in DB.

            //    context.SaveChanges();

            //    Console.WriteLine("==After SaveChanges()==");
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//UnChanged
            //    Console.WriteLine($"Name After Save Changes => {employee01.Name}");//"Amr" -> In App And DB.

            //}

            #endregion

            #region 03.1 - If Change Tracking on object is Disabled

            //var employee01 = context.Employees.AsNoTracking().FirstOrDefault(e => e.Salary == 40000);//Translated As Top(1) in SQL

            //if (employee01 is not null)
            //{
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//Detached[default]
            //    Console.WriteLine($"[Code: {employee01.Code}] - [Name: {employee01.Name}] - [Salary: {employee01.Salary}] - [NetSalary: {employee01.NetSalary}] - [Email: {employee01.Email}] - [password: {employee01.password}]");
            //    //

            //    employee01.Name = "Ahmed";//Change

            //    Console.WriteLine("==After Change==");
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//Detached[default]
            //    Console.WriteLine($"Name After Change => {employee01.Name}");//"Ahmed" - But still "Amr" In DB.

            //    context.SaveChanges();

            //    Console.WriteLine("==After SaveChanges()==");
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//Detached[default]
            //    Console.WriteLine($"Name After Save Changes => {employee01.Name}");//"Ahmed" - But still "Amr" In DB - because you disable change tracking on this object.

            //}

            #endregion

            #endregion

            #region 04 - Delete/Remove Data/row/object from table in DB.

            //var employee01 = context.Employees.FirstOrDefault(e => e.Salary == 40000);//Translated As Top(1) in SQL

            //if (employee01 is not null)
            //{
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//UnChanged

            //    context.Employees.Remove(employee01);//Approach01 - Not really Delete the object From DB - it just convert the change tracker state of object from UnChanged to Deleted - Deleted Locally in APP.
            //    context.Set<Employee>().Remove(employee01);//Approach02 - Not really Delete the object From DB - it just convert the change tracker state of object from UnChanged to Deleted - Deleted Locally in APP.
            //    context.Remove(employee01);//Approach03 - Not really Delete the object From DB - it just convert the change tracker state of object from UnChanged to Deleted - Deleted Locally in APP.
            //    context.Entry<Employee>(employee01).State = EntityState.Deleted;//Approach04 - Not really Delete the object From DB - it just convert the change tracker state of object from UnChanged to Deleted - Deleted Locally in APP.

            //    Console.WriteLine("==State After Remove==");
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//Deleted

            //    context.SaveChanges();

            //    Console.WriteLine("==State After SaveChanges()");
            //    Console.WriteLine(context.Entry<Employee>(employee01).State);//Detached - because it deleted from database - not found in DB

            //}

            ////If you run App again after delete and save changes, the console screen will be empty because the "employee01 is null"
            ////There is no objects in Table Employees in DB match this condition. 
            
            #endregion

            #endregion

        }
    }
}
