namespace Demo
{
    internal class Program
    {
        static void Main(string[] args)
        {
            #region Part 07 Mapping Ways  - 2. Data Annotations

            ///There Are 4 Ways That EF core Support For Mapping Classes [DbContext - Domain Models] To [Tables - Views] in DB
            /// 1- By Convention
            /// 2- Data Annotations [Set Of Attributes[Classes]]
            /// 3- Fluent API
            ///
            ///We Will Discuss The Data Annotations [Set of Attributes] Way in This Context => 
            /// - Attributes use the decorator design pattern As behavior Not Implementation [Attributes Classes Internally not using Decorator Design Pattern]
            ///    Mean That I have Property not has specific behavior and i need this property to use this behavior
            ///    So I Make Attribute on it [Add to it specific behavior].
            ///    Make Decoration to it.
            ///    So Attributes are set of Behaviors.
            /// -With other meaning => I have property in class Employee Called "Code" And I need it to mapped as PK Column in DB
            ///   But With Convention Way This not will be mapped as PK
            ///   Because In Convention Way The PK column Must be named "Id" or "ModelName+Id".
            ///   So We let this Property "Code" to have new behavior to be "PK" by Make Attribute [KeyAttribute] on it [Use Data Annotation Way] to be mapped as PK Column.
            ///
            ///I don't work using specific Way => I understand the Convention Way Will
            ///And then if i need the mapping of this convention way => Ok use it.
            ///If You need to add extra or change the default behavior => use another way to meet your needs.
            ///
            ///When We will Work On ASP.NET Core Web Application
            /// -Every Class Model Will Be has View[HTML Page] Specific for this class
            /// -Throw This page the user can create new instance from the class and
            /// -And inside this page there is HTML Input for each and every property to let user enter values to those properties
            /// -So if i need to make validations on this input values - I make Validation Data Annotations [Properties] on top of the property in the class model.
            ///
            ///If there is property in Domain Model Class use the identity(1,1)
            ///And you need to add data in Database 
            ///And make object from class like Employee
            ///You can't set this property with value because it is auto generated by sql server service.
            ///
            ///Any Data Annotation that used as validation has default error Message - but you can override this default error message.

            #endregion
        }
    }
}
